//common constants
export const LOADING = "LOADING";
export const LOADED = "LOADED";
export const ERROR = "ERROR";
export const RESET = "RESET";

//connections constants
export const SET_CONNECTIONS = "SET_CONNECTIONS";
export const SET_CONNECTION = "SET_CONNECTION";
export const SET_INVITATION = "SET_INVITATION";
export const ACCEPT_INVITATION = "ACCEPT_INVITATION";

//schemas constants
export const SET_SCHEMAS = "SET_SCHEMAS";
export const SET_SCHEMA_IDS = "SET_SCHEMA_IDS";
export const ADD_NEW_SCHEMA = "ADD_NEW_SCHEMA";
export const ADD_NEW_SCHEMA_ID = "ADD_NEW_SCHEMA_ID";

//Credential constants
export const SELECTED_CONNECTION = "SELECTED_CONNECTION";
export const SELECTED_CREDENTIAL_DEFINITION = "SELECTED_CREDENTIAL_DEFINITION";
export const SET_SELECTED_CONNECTION = "SET_SELECTED_CONNECTION";
export const SET_SELECTED_CREDENTIAL_DEFINITION =
  "SET_SELECTED_CREDENTIAL_DEFINITION";
export const SET_CREDENTIALS_IDS = "SET_CREDENTIALS_IDS";

//Proof constants
export const SET_PROOF_LIST = "SET_PROOF_LIST";
export const SET_FOUND_CREDENTIALS = "SET_FOUND_CREDENTIALS";
export const SET_REQUESTED_PREDICATES = "SET_REQUESTED_PREDICATES";
export const SET_REQUESTED_ATTRIBUTES = "SET_REQUESTED_ATTRIBUTES";
export const SET_CURRENT_CREDENTIAL = "SET_CURRENT_CREDENTIAL";
export const SEND_PROOF_REQUEST = "SEND_PROOF_REQUEST";
export const ADD_PROOF_REQUEST = "ADD_PROOF_REQUEST";
export const UPDATE_PROOF_REQUEST = "UPDATE_PROOF_REQUEST";
